export const Scope = Object.freeze({
  USER_FOLLOW_READ: 'user-follow-read',
  PLAYLIST_MODIFY_PRIVATE: 'playlist-modify-private',
  PLAYLIST_MODIFY_PUBLIC: 'playlist-modify-public',
});

export const FieldName = Object.freeze({
  START_DATE: 'startDate',
  END_DATE: 'endDate',
  NAME: 'name',
  NAME_CUSTOM: 'nameCustom',
  DESCRIPTION: 'description',
  VISIBILITY: 'visibility',
  RELEASES_COUNT: 'releasesCount',
});

export const SpotifyEntity = Object.freeze({
  PLAYLIST: 'playlist',
  TRACK: 'track',
});

export const Moment = Object.freeze({
  SECOND: 'second',
  DAY: 'day',
  WEEK: 'week',
  ISO_WEEK: 'isoWeek',
  MONTH: 'month',
});

export const MomentFormat = Object.freeze({
  ISO_DATE: 'YYYY-MM-DD',
});

export const AlbumGroup = Object.freeze({
  album: 'Albums',
  single: 'Singles',
  compilation: 'Compilations',
  appears_on: 'Appearances',
});

export const Market = Object.freeze({
  DZ: 'Algeria',
  AD: 'Andorra',
  AR: 'Argentina',
  AU: 'Australia',
  AT: 'Austria',
  BH: 'Bahrain',
  BE: 'Belgium',
  BO: 'Bolivia',
  BR: 'Brazil',
  BG: 'Bulgaria',
  CA: 'Canada',
  CL: 'Chile',
  CO: 'Colombia',
  CR: 'Costa Rica',
  CY: 'Cyprus',
  CZ: 'Czech Republic',
  DK: 'Denmark',
  DO: 'Dominican Republic',
  EC: 'Ecuador',
  EG: 'Egypt',
  SV: 'El Salvador',
  EE: 'Estonia',
  FI: 'Finland',
  FR: 'France',
  DE: 'Germany',
  GR: 'Greece',
  GT: 'Guatemala',
  HN: 'Honduras',
  HK: 'Hong Kong',
  HU: 'Hungary',
  IS: 'Iceland',
  IN: 'India',
  ID: 'Indonesia',
  IE: 'Ireland',
  IL: 'Israel',
  IT: 'Italy',
  JP: 'Japan',
  JO: 'Jordan',
  KW: 'Kuwait',
  LV: 'Latvia',
  LB: 'Lebanon',
  LI: 'Liechtenstein',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  MY: 'Malaysia',
  MT: 'Malta',
  MX: 'Mexico',
  MC: 'Monaco',
  MA: 'Morocco',
  NL: 'Netherlands',
  NZ: 'New Zealand',
  NI: 'Nicaragua',
  NO: 'Norway',
  OM: 'Oman',
  PS: 'Palestine',
  PA: 'Panama',
  PY: 'Paraguay',
  PE: 'Peru',
  PH: 'Philippines',
  PL: 'Poland',
  PT: 'Portugal',
  QA: 'Qatar',
  RO: 'Romania',
  SA: 'Saudi Arabia',
  SG: 'Singapore',
  SK: 'Slovakia',
  ZA: 'South Africa',
  ES: 'Spain',
  SE: 'Sweden',
  CH: 'Switzerland',
  TW: 'Taiwan',
  TH: 'Thailand',
  TN: 'Tunisia',
  TR: 'Turkey',
  AE: 'United Arab Emirates',
  GB: 'United Kingdom',
  US: 'United States',
  UY: 'Uruguay',
  VN: 'Vietnam',
});
