export { default as Settings } from './Settings'
export { default as GeneralSettings } from './GeneralSettings'
export { default as AppearanceSettings } from './AppearanceSettings'
export { default as AutomationSettings } from './AutomationSettings'
export { default as BackupSettings } from './BackupSettings'
export { default as AboutSettings } from './AboutSettings'
